# config.yaml file
current_config:
    current

current:
    name:
    sql:
    storage:
    target_metric:
    query_predict_data:
    extra: []
    mlflow:
        registered_model_name:
        model_version:
        tracking_uri:
        experiment_name:
        tags: